services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'spring-intro'
      MYSQL_USER: 'intro'
      MYSQL_PASSWORD: 'intro'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
volumes:
  mysql_data: