spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring-intro?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: intro
        password: intro

